import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import App from "next/app";
import AppSidebar from "@/components/ui/AppSidebar";
import Navbar from "@/components/ui/Navbar";
import ShowUnlessRoot from "@/components/ui/ShowUnlessRoot"
import { ThemeProvider } from "@/components/providers/Themeprovider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"
  const authCookie = cookieStore.get("auth")?.value ?? null
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <SidebarProvider defaultOpen={defaultOpen}>
            {/* Server-side check: only render sidebar/navbar when auth cookie exists */}
            {authCookie ? (
              <>
                <ShowUnlessRoot>
                  <AppSidebar />
                </ShowUnlessRoot>
                <main className="w-full">
                  <ShowUnlessRoot>
                    <Navbar />
                  </ShowUnlessRoot>
                  <div className="px-4">{children}</div>
                </main>
              </>
            ) : (
              // no auth cookie: render children full width (login page)
              <main className="w-full">
                <div className="px-4">{children}</div>
              </main>
            )}
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
